-- =============================================================================
-- DBMS Name               :    Teradata
-- Script Name             :    recreate_dssdemo.sql
-- Description             :    Creates a sample Teradata environment for RED
-- Usage                   :    Run this procedure as a Teradata administrator user
--                              with sufficient authority to create databases and
--                              users.
--
-- WhereScape Limited, inc. All rights reserved. (C) Copyright 1996-2016
-- =============================================================================
--
-- Notes                   1) This is a sample script only.
--                         2) This script assumes the RED environment will be
--                            created in the SysDBA database, if this is not
--                            desired, globally change SysDBA to the required
--                            database.
--
-- =============================================================================
-- Notes / History
--
-- JML  04-MAY-2015     Version 1.0
--      07-AUG-2015     Version-1.1 - Added RED_LOAD,RED_DATASTORE and RED_TEMP schemas
--                                  - Fixed PERMANENT option issue for CREATE USER statement
--                                  - Updated options for CREATE USER statement
--                                  - Updated permissions for VIEW schemas
-- RS   25-Jan-2016     Version 6.5.2 Removed grant to select DBC.ErrorMsgs
-- =============================================================================

CREATE DATABASE RED_REPOSITORY FROM SysDBA AS PERM=10e9;
CREATE DATABASE RED_LOAD FROM SysDBA AS PERM=10e9;
CREATE DATABASE RED_STAGE FROM SysDBA AS PERM=10e9;
CREATE DATABASE RED_MODEL FROM SysDBA AS PERM=10e9;
CREATE DATABASE RED_AGGSUM FROM SysDBA AS PERM=10e9;
CREATE DATABASE RED_BASE_VIEW FROM SysDBA AS PERM=10e9;
CREATE DATABASE RED_USER_VIEW FROM SysDBA AS PERM=10e9;
CREATE DATABASE RED_DATA_STORE FROM SysDBA AS PERM=10e9;
CREATE DATABASE RED_TEMP FROM SysDBA AS PERM=10e9;

CREATE ROLE RED_DEVELOPER_ROLE;
CREATE USER DSSDEMO FROM SysDBA AS PERMANENT = 10e9, SPOOL = 10e9, TEMPORARY = 10e9, PASSWORD = wsl, COLLATION = ASCII, DEFAULT CHARACTER SET LATIN;

GRANT SELECT, INSERT, UPDATE, DELETE, TABLE, VIEW, SHOW, MACRO, PROCEDURE, STATISTICS, EXECUTE, EXECUTE PROCEDURE ON RED_REPOSITORY TO RED_DEVELOPER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TABLE, VIEW, SHOW, STATISTICS ON RED_LOAD TO RED_DEVELOPER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TABLE, VIEW, SHOW, STATISTICS ON RED_STAGE TO RED_DEVELOPER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TABLE, VIEW, SHOW, STATISTICS ON RED_MODEL TO RED_DEVELOPER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TABLE, VIEW, SHOW, STATISTICS ON RED_AGGSUM TO RED_DEVELOPER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TABLE, VIEW, SHOW, STATISTICS ON RED_DATA_STORE TO RED_DEVELOPER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TABLE, VIEW, SHOW, STATISTICS ON RED_TEMP TO RED_DEVELOPER_ROLE;
GRANT SELECT, VIEW, SHOW ON RED_BASE_VIEW TO RED_DEVELOPER_ROLE;
GRANT SELECT, VIEW, SHOW ON RED_USER_VIEW TO RED_DEVELOPER_ROLE;

GRANT EXECUTE PROCEDURE ON RED_REPOSITORY TO RED_REPOSITORY WITH GRANT OPTION;

GRANT EXECUTE, SELECT, INSERT, UPDATE, DELETE ON RED_LOAD TO RED_REPOSITORY;
GRANT EXECUTE, SELECT, INSERT, UPDATE, DELETE ON RED_STAGE TO RED_REPOSITORY;
GRANT EXECUTE, SELECT, INSERT, UPDATE, DELETE ON RED_MODEL TO RED_REPOSITORY;
GRANT EXECUTE, SELECT, INSERT, UPDATE, DELETE ON RED_AGGSUM TO RED_REPOSITORY;
GRANT EXECUTE, SELECT, INSERT, UPDATE, DELETE ON RED_BASE_VIEW TO RED_REPOSITORY;
GRANT EXECUTE, SELECT, INSERT, UPDATE, DELETE ON RED_USER_VIEW TO RED_REPOSITORY;
GRANT EXECUTE, SELECT, INSERT, UPDATE, DELETE ON RED_DATA_STORE TO RED_REPOSITORY;
GRANT EXECUTE, SELECT, INSERT, UPDATE, DELETE ON RED_TEMP TO RED_REPOSITORY;

GRANT SELECT ON RED_MODEL TO RED_BASE_VIEW WITH GRANT OPTION;
GRANT SELECT ON RED_MODEL TO RED_USER_VIEW WITH GRANT OPTION;
GRANT SELECT ON RED_AGGSUM TO RED_BASE_VIEW WITH GRANT OPTION;
GRANT SELECT ON RED_AGGSUM TO RED_USER_VIEW WITH GRANT OPTION;

GRANT SELECT ON DBC.TABLESV to RED_DEVELOPER_ROLE;
GRANT SELECT ON DBC.COLUMNSV to RED_DEVELOPER_ROLE;
GRANT SELECT ON SYSLIB.SQLRESTRICTEDWORDS to RED_DEVELOPER_ROLE;

GRANT RED_DEVELOPER_ROLE TO DSSDEMO WITH ADMIN OPTION;
MODIFY USER DSSDEMO AS DEFAULT ROLE=ALL;
